### ISSUE TITLE
Forge pach

### ISSUE THREAD

**Issue by aws0jam** [MrLetsplay2003/ShittyAuthPatcher#2]
Hello can i pach forge server file with this tool ?

**Comment by MrLetsplay2003** [comment]
It should work if you patch the correct JAR file, but I don't know which JAR file. Currently, I don't have specific instructions for Forge, but I might add them in the future.

However, I first need to look into which JAR needs to be patched for Forge

**Comment by MrLetsplay2003** [comment]
Just tested it on Forge 1.20.1. Patching `libraries/com/mojang/authlib/VERSION/authlib-VERSION.jar` using the normal server patch seems to work

**Comment by aws0jam** [comment]
Thanks! We'll try it as soon as we have time
